#!/usr/bin/python3

import parent
import testlib

class TestVersion(testlib.MachineCase):
    def setUp(self):
        super().setUp()

        self.machine.execute("cat /etc/redhat-release")


    def testVersion(self):
        m = self.machine

        kernel_ver = m.execute("uname -r").rstrip()
        self.assertEqual(kernel_ver, "4.18.0-218.el8.x86_64")


if __name__ == '__main__':
    testlib.test_main()
