#!/usr/bin/python3

import parent
import testlib


class TestVersion(testlib.MachineCase):
    def setUp(self):
        super().setUp()

        self.machine.execute("cat /etc/redhat-release")

    def testVersion(self):
        m = self.machine

        m.upload(["files/test_file1", "files/test_file2"], "/tmp")
        # relative path is "$(pwd)/test"
        m.download("/tmp/test_file1", "./")
        m.download_dir("/etc/yum.repos.d", "./")

        m.write("/tmp/test_file1", "hello kita-test!")
        self.sed_file('s/hello/hi/', "/tmp/test_file1")

        m.write("/tmp/test_file2", "I'll be restored after change")
        self.restore_file("/tmp/test_file2")
        # do any changes on /tmp/test_file1
        # It'll be restored after test

        self.restore_dir("/etc/yum.repos.d")
        # do any changes on content in /etc/yum.repos.d
        # this folder will be restored after  test

        # check sed result
        file1_content = m.execute("cat /tmp/test_file1")
        self.assertEqual(file1_content, "hi kita-test!")
        # strip the tail "\n"
        kernel_ver = m.execute("uname -r").rstrip()
        self.assertEqual(kernel_ver, "4.18.0-218.el8.x86_64")


if __name__ == '__main__':
    testlib.test_main()
